In [187]:
import pandas as pd
import numpy as np

In [188]:
df_vendas = pd.read_csv("../data/vendas.csv")

In [189]:
#Primeiras linhas
df_vendas.head()

   ID_Venda         Produto  Quantidade  Preco_Unitario  Data_Venda
0         1   Cadeira Gamer          29         1202.86  2023-05-01
1         2  Roteador Wi-Fi          17          737.71  2025-10-02
2         3  Roteador Wi-Fi          12          760.47  2023-04-28
3         4   Cadeira Gamer           4          875.04  2024-09-30
4         5   Controle Xbox          23          967.56  2024-06-09

In [190]:
#Ultimas linhas
df_vendas.tail()

     ID_Venda         Produto  Quantidade  Preco_Unitario  Data_Venda
995       996      Impressora          11          878.36  2024-04-20
996       997       Óculos VR           3         1173.65  2024-08-23
997       998  Fone de ouvido          13          109.07  2024-08-11
998       999  HD Externo 1TB          16          691.38  2023-07-05
999      1000  Câmera Digital           7         1201.48  2024-07-03

In [191]:
#Verificando informações ferais do DF
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        1000 non-null   int64
 1   Produto         1000 non-null   object
 2   Quantidade      1000 non-null   int64
 3   Preco_Unitario  1000 non-null   float64
 4   Data_Venda      1000 non-null   object
dtypes: float64(1), int64(2), object(2)
memory usage: 39.2+ KB

In [192]:
df_vendas.describe()

          ID_Venda  Quantidade  Preco_Unitario
count  1000.000000   1000.0000     1000.000000
mean    500.500000     15.2180      762.092790
std     288.819436      8.2034      429.833655
min       1.000000      1.0000       21.630000
25%     250.750000      8.0000      390.687500
50%     500.500000     15.0000      761.285000
75%     750.250000     22.0000     1136.905000
max    1000.000000     29.0000     1498.950000

In [193]:
#Criar uma coluna chamada Receita Ttotal (Quantidade * Preco_Unitario)
df_vendas['Receita_Total'] = df_vendas['Quantidade'] * df_vendas['Preco_Unitario']
df_vendas.head()

,ID_Venda,Produto,Quantidade,Preco_Unitario,Data_Venda,Receita_Total
0,1,Cadeira Gamer,29,1202.86,2023-05-01,34882.94
1,2,Roteador Wi-Fi,17,737.71,2025-10-02,12541.07
2,3,Roteador Wi-Fi,12,760.47,2023-04-28,9125.64
3,4,Cadeira Gamer,4,875.04,2024-09-30,3500.16
4,5,Controle Xbox,23,967.56,2024-06-09,22253.88

In [194]:
#Selecionar apenas as colunas Produto e Receita Total
df_vendas[["Produto", "Receita_Total"]].head()

          Produto  Receita_Total
0   Cadeira Gamer       34882.94
1  Roteador Wi-Fi       12541.07
2  Roteador Wi-Fi        9125.64
3   Cadeira Gamer        3500.16
4   Controle Xbox       22253.88

In [195]:
#Linhas onde a quantidade é maior que 20
df_vendas[df_vendas["Quantidade"] > 20].head()

,ID_Venda,Produto,Quantidade,Preco_Unitario,Data_Venda,Receita_Total
0,1,Cadeira Gamer,29,1202.86,2023-05-01,34882.94
4,5,Controle Xbox,23,967.56,2024-06-09,22253.88
15,16,Cadeira Gamer,25,1050.08,2024-11-02,26252.00
17,18,Cadeira Gamer,21,1359.72,2024-08-28,28554.12
18,19,Câmera Digital,26,476.79,2023-10-29,12396.54

In [196]:
#loc (selecionar linhas e colunas por rótulo (Produto = 'Monitor'))

df_vendas.loc[df_vendas["Produto"] == "Monitor", ["ID_Venda", "Quantidade", "Preco_Unitario"]].head()

     ID_Venda  Quantidade  Preco_Unitario
28         29          10          331.83
54         55          28           88.17
138       139           6          951.61
170       171           5         1399.88
185       186          27          647.74

In [197]:
#Selecionar as primeiras 3 linhas e as colunas de 1 a 3
df_vendas.iloc[0:3, 1:4]

          Produto  Quantidade  Preco_Unitario
0   Cadeira Gamer          29         1202.86
1  Roteador Wi-Fi          17          737.71
2  Roteador Wi-Fi          12          760.47

In [198]:
#Cálculos (Pandas e Numpy)
#Descobrir o faturamento (Receita Total)
print(f"Receita Total de Vendas da Loja: {df_vendas["Receita_Total"].sum():.2f}")

Receita Total de Vendas da Loja: 11610833.99

In [199]:
#Preço médio unitário dos produtos
print(f"O Preço médio unitário dos produtos é: {df_vendas["Preco_Unitario"].mean():.2f}")

O Preço médio unitário dos produtos é: 762.09

In [200]:
#Quantidade mínima e máxima de produtos vendidos
print(f"Quantidade minima de produtos vendidos: {df_vendas["Quantidade"].min()}")
print(f"Quantidade maxima de produtos vendidos: {df_vendas["Quantidade"].max()}")

Quantidade minima de produtos vendidos: 1
Quantidade maxima de produtos vendidos: 29

In [201]:
#Simular valores ausentes dentro do DF
df_vendas_com_nan = df_vendas.copy()
df_vendas_com_nan.loc[df_vendas_com_nan.sample(frac=0.05).index,'Preco_Unitario'] = np.nan
df_vendas_com_nan.loc[df_vendas_com_nan.sample(frac=0.03).index,'Quantidade'] = np.nan

In [202]:
#Verificar se existe valores ausentes
df_vendas_com_nan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        1000 non-null   int64
 1   Produto         1000 non-null   object
 2   Quantidade      970 non-null    float64
 3   Preco_Unitario  950 non-null    float64
 4   Data_Venda      1000 non-null   object
 5   Receita_Total   1000 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 47.0+ KB

In [203]:
#Verificar se existe valores ausentes
df_vendas_com_nan.isna().sum()

ID_Venda           0
Produto            0
Quantidade        30
Preco_Unitario    50
Data_Venda         0
Receita_Total      0
dtype: int64

In [204]:
#Preencher os valores ausentes com a média da coluna Quantidade (fillna)
df_vendas_preenchido = df_vendas_com_nan.copy()
media_qtd = df_vendas_preenchido['Quantidade'].mean()
df_vendas_preenchido['Quantidade'].fillna(media_qtd, inplace=True)

C:\Users\Lucas\AppData\Local\Temp\ipykernel_14516\3900981844.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_vendas_preenchido['Quantidade'].fillna(media_qtd, inplace=True)

In [205]:
df_vendas_preenchido.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        1000 non-null   int64
 1   Produto         1000 non-null   object
 2   Quantidade      1000 non-null   float64
 3   Preco_Unitario  950 non-null    float64
 4   Data_Venda      1000 non-null   object
 5   Receita_Total   1000 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 47.0+ KB

In [206]:
#Remover valores ausentes encontrados em Preço Unitario
df_vendas_limpo = df_vendas_preenchido.dropna(subset=['Preco_Unitario'])

In [207]:
df_vendas_limpo.head()

,ID_Venda,Produto,Quantidade,Preco_Unitario,Data_Venda,Receita_Total
0,1,Cadeira Gamer,29.0,1202.86,2023-05-01,34882.94
1,2,Roteador Wi-Fi,17.0,737.71,2025-10-02,12541.07
2,3,Roteador Wi-Fi,12.0,760.47,2023-04-28,9125.64
3,4,Cadeira Gamer,4.0,875.04,2024-09-30,3500.16
4,5,Controle Xbox,23.0,967.56,2024-06-09,22253.88

In [208]:
#Agrupar por produtos e calcular quantidade e receita total por produto
vendas_por_produto = df_vendas_limpo.groupby('Produto').agg(
    Quantidade_total=("Quantidade", "sum"),
    Receita_Total=("Receita_Total", "sum")
).reset_index()
print(vendas_por_produto)

            Produto  Quantidade_total  Receita_Total
0     Cadeira Gamer        725.186598      633347.68
1      Caixa de Som        835.186598      695623.92
2      Controle PS5        642.000000      451535.38
3     Controle Xbox        813.000000      680727.03
4    Câmera Digital        887.373196      642743.10
5    Fone de ouvido        599.000000      395827.68
6    HD Externo 1TB        972.373196      781614.16
7        Impressora        592.000000      500819.87
8   Memória RAM 8GB        623.373196      507261.90
9        Mesa Gamer        680.000000      485745.28
10        Microfone        732.746392      462918.18
11          Monitor        514.000000      452825.56
12            Mouse        842.186598      707543.50
13   Placa de Vídeo        733.306186      617721.92
14      Processador        425.000000      293444.42
15   Roteador Wi-Fi        855.373196      611897.14
16        SSD 256GB        848.373196      670395.14
17          Teclado        771.000000      506485.09
18           Webcam        668.186598      459803.99
19        Óculos VR        757.373196      574025.25

In [209]:
#Ordenar os valores por quantidade total para saber o produto mais vendida
produto_mais_vendido = vendas_por_produto.sort_values(by="Quantidade_total", ascending=False).iloc[0]
print(produto_mais_vendido)

Produto             HD Externo 1TB
Quantidade_total        972.373196
Receita_Total            781614.16
Name: 6, dtype: object

In [210]:
#Ordenar os valores por receita total para saber o maior total gerado
produto_maior_receita = vendas_por_produto.sort_values(by="Receita_Total", ascending=False).iloc[0]
print(produto_maior_receita)

Produto             HD Externo 1TB
Quantidade_total        972.373196
Receita_Total            781614.16
Name: 6, dtype: object

In [211]:
df_produtos = pd.read_csv("../data/produtos.csv")

In [212]:
df_produtos.head()

          Produto    Categoria
0         Teclado  Periféricos
1           Mouse  Periféricos
2         Monitor    Monitores
3          Webcam  Periféricos
4  Fone de ouvido        Áudio

In [213]:
#Converter a coluna Data_Venda para o tipo correto de data
df_vendas_limpo["Data_Venda"] = pd.to_datetime(df_vendas_limpo["Data_Venda"])

C:\Users\Lucas\AppData\Local\Temp\ipykernel_14516\3363620298.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vendas_limpo["Data_Venda"] = pd.to_datetime(df_vendas_limpo["Data_Venda"])

In [214]:
#Analisar as vendas por mês
df_vendas_limpo["Mes_Venda"] = df_vendas_limpo["Data_Venda"].dt.month

C:\Users\Lucas\AppData\Local\Temp\ipykernel_14516\63686739.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vendas_limpo["Mes_Venda"] = df_vendas_limpo["Data_Venda"].dt.month

In [215]:
#Agrupar por mês para calcular a receita total mês a mês
vendas_por_mes = df_vendas_limpo.groupby("Mes_Venda")["Receita_Total"].sum().reset_index()
print("\nVendas por Mês")
print(vendas_por_mes)

Vendas por Mês
    Mes_Venda  Receita_Total
0           1      969303.36
1           2     1214544.25
2           3      894502.46
3           4      944896.78
4           5     1166864.46
5           6      983392.43
6           7      854652.53
7           8     1032129.31
8           9     1061258.69
9          10      873530.88
10         11      532354.55
11         12      604876.49

In [216]:
#Combinar os dados de Vendas e Produtos
df_merge = pd.merge(df_vendas_limpo, df_produtos, on='Produto', how='left')
print(df_merge)

     ID_Venda         Produto  Quantidade  Preco_Unitario Data_Venda  \
0           1   Cadeira Gamer        29.0         1202.86 2023-05-01
1           2  Roteador Wi-Fi        17.0          737.71 2025-10-02
2           3  Roteador Wi-Fi        12.0          760.47 2023-04-28
3           4   Cadeira Gamer         4.0          875.04 2024-09-30
4           5   Controle Xbox        23.0          967.56 2024-06-09
..        ...             ...         ...             ...        ...
945       996      Impressora        11.0          878.36 2024-04-20
946       997       Óculos VR         3.0         1173.65 2024-08-23
947       998  Fone de ouvido        13.0          109.07 2024-08-11
948       999  HD Externo 1TB        16.0          691.38 2023-07-05
949      1000  Câmera Digital         7.0         1201.48 2024-07-03

     Receita_Total  Mes_Venda      Categoria
0         34882.94          5         Móveis
1         12541.07         10          Redes
2          9125.64          4          Redes
3          3500.16          9         Móveis
4         22253.88          6          Games
..             ...        ...            ...
945        9661.96          4    Periféricos
946        3520.95          8          Games
947        1417.91          8          Áudio
948       11062.08          7  Armazenamento
949        8410.36          7        Câmeras

[950 rows x 8 columns]

In [217]:
#Análise de vendas por categoria (Receita Total por categoria)
vendas_por_categoria = df_merge.groupby('Categoria')['Receita_Total'].sum().reset_index()
print(vendas_por_categoria)

       Categoria  Receita_Total
0  Armazenamento     1452009.30
1    Componentes     1418428.24
2        Câmeras      642743.10
3          Games     1706287.66
4      Monitores      452825.56
5         Móveis     1119092.96
6    Periféricos     2174652.45
7          Redes      611897.14
8          Áudio     1554369.78

In [218]:
#Filtragem dentro do DataFrame
df_merge.head()

,ID_Venda,Produto,Quantidade,Preco_Unitario,Data_Venda,Receita_Total,Mes_Venda,Categoria
0,1,Cadeira Gamer,29.0,1202.86,2023-05-01,34882.94,5,Móveis
1,2,Roteador Wi-Fi,17.0,737.71,2025-10-02,12541.07,10,Redes
2,3,Roteador Wi-Fi,12.0,760.47,2023-04-28,9125.64,4,Redes
3,4,Cadeira Gamer,4.0,875.04,2024-09-30,3500.16,9,Móveis
4,5,Controle Xbox,23.0,967.56,2024-06-09,22253.88,6,Games

In [219]:
#Filtrar por coluna (Produto, Quantidade, Receita Total)
df_colunas_filtradas = df_merge.filter(items=["Produto", "Quantidade", "Receita_Total"])

In [220]:
df_colunas_filtradas

            Produto  Quantidade  Receita_Total
0     Cadeira Gamer        29.0       34882.94
1    Roteador Wi-Fi        17.0       12541.07
2    Roteador Wi-Fi        12.0        9125.64
3     Cadeira Gamer         4.0        3500.16
4     Controle Xbox        23.0       22253.88
..              ...         ...            ...
945      Impressora        11.0        9661.96
946       Óculos VR         3.0        3520.95
947  Fone de ouvido        13.0        1417.91
948  HD Externo 1TB        16.0       11062.08
949  Câmera Digital         7.0        8410.36

[950 rows x 3 columns]

In [221]:
#Filtragem mais avançadas (Produto Teclado, quantidade > 10)
df_query = df_merge.query('Produto == "Teclado" and Quantidade > 10')
df_query

,ID_Venda,Produto,Quantidade,Preco_Unitario,Data_Venda,Receita_Total,Mes_Venda,Categoria
64,70,Teclado,23.0,1159.02,2025-03-18,26657.46,3,Periféricos
66,72,Teclado,27.0,94.04,2025-07-17,2539.08,7,Periféricos
98,108,Teclado,26.0,715.91,2024-03-17,18613.66,3,Periféricos
109,119,Teclado,25.0,100.25,2024-10-28,2506.25,10,Periféricos
140,151,Teclado,25.0,1471.75,2023-10-28,36793.75,10,Periféricos
141,152,Teclado,26.0,183.43,2025-03-20,4769.18,3,Periféricos
288,305,Teclado,15.0,233.59,2024-12-16,3503.85,12,Periféricos
315,332,Teclado,21.0,1135.01,2025-03-07,23835.21,3,Periféricos
322,340,Teclado,28.0,665.65,2025-02-24,18638.20,2,Periféricos
342,360,Teclado,16.0,300.38,2025-08-05,4806.08,8,Periféricos
382,401,Teclado,25.0,1257.56,2023-03-07,31439.00,3,Periféricos
473,496,Teclado,14.0,717.33,2025-07-15,10042.62,7,Periféricos
483,506,Teclado,27.0,1027.91,2023-02-13,27753.57,2,Periféricos
512,535,Teclado,17.0,602.49,2023-06-22,10242.33,6,Periféricos
521,545,Teclado,11.0,638.11,2025-09-23,7019.21,9,Periféricos
527,553,Teclado,27.0,380.90,2024-02-08,10284.30,2,Periféricos
532,559,Teclado,24.0,251.94,2024-03-01,6046.56,3,Periféricos
547,574,Teclado,17.0,985.04,2024-07-17,16745.68,7,Periféricos
573,602,Teclado,20.0,460.50,2023-09-19,9210.00,9,Periféricos
578,607,Teclado,20.0,403.52,2023-05-09,8070.40,5,Periféricos
618,649,Teclado,11.0,47.02,2023-01-12,517.22,1,Periféricos
648,680,Teclado,17.0,1443.00,2023-08-01,24531.00,8,Periféricos
654,687,Teclado,18.0,1174.57,2023-08-26,21142.26,8,Periféricos
664,697,Teclado,29.0,571.98,2023-01-07,16587.42,1,Periféricos
667,700,Teclado,24.0,44.12,2025-08-18,1058.88,8,Periféricos
719,759,Teclado,24.0,74.73,2024-11-13,1793.52,11,Periféricos
790,837,Teclado,16.0,1043.42,2023-04-12,16694.72,4,Periféricos
809,856,Teclado,20.0,675.60,2024-08-15,13512.00,8,Periféricos
855,904,Teclado,17.0,47.63,2023-12-06,809.71,12,Periféricos
875,924,Teclado,21.0,508.62,2023-05-24,10681.02,5,Periféricos
893,944,Teclado,25.0,919.71,2025-02-04,22992.75,2,Periféricos
920,971,Teclado,14.0,841.53,2023-04-27,11781.42,4,Periféricos